spring:
  #redis
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 100000 #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 100 #连接池最大连接数(使用负值表示没有限制)
        max-wait: 1000  #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 20 #连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
#自定义参数
redis:
  session:
    timeout: 1800
  key:
    prefix: allowance_